// <auto-generated />
using System;
using FlashcardService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlashcardService.Infrastructure.Migrations
{
    [DbContext(typeof(DBContextFlashcard))]
    [Migration("20260301042603_InitialCreateDBFlashcardService")]
    partial class InitialCreateDBFlashcardService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlashcardService.Domain.EntitiesFrashcard.Flashcard", b =>
                {
                    b.Property<Guid>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FlashcardDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FlashcardName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("FlashcardType")
                        .HasColumnType("boolean");

                    b.HasKey("FlashcardId");

                    b.ToTable("Flashcards", (string)null);
                });

            modelBuilder.Entity("FlashcardService.Domain.EntitiesFrashcard.Vocabulary", b =>
                {
                    b.Property<Guid>("VobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Define")
                        .HasColumnType("text");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Terminology")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VobId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("Vocabularies", (string)null);
                });

            modelBuilder.Entity("FlashcardService.Domain.EntitiesFrashcard.Vocabulary", b =>
                {
                    b.HasOne("FlashcardService.Domain.EntitiesFrashcard.Flashcard", "flashcard")
                        .WithMany("Vocabularies")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flashcard");
                });

            modelBuilder.Entity("FlashcardService.Domain.EntitiesFrashcard.Flashcard", b =>
                {
                    b.Navigation("Vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
